version: "3.5"
services:
  php:
    build:
      dockerfile: Dockerfile
      context: docker
    container_name: magento23
    depends_on:
      - mysql
    networks:
      magento:
        ipv4_address: 173.26.2.5
    ports:
        - "82:80"
        - "9000:9000"
    volumes:
        - //c/Users/path-here/www:/var/www/html
  mysql:
    image: mysql:5.7
    container_name: magento23_mysql
    command: --sql_mode="" --innodb_use_native_aio=0
    networks:
      magento:
        ipv4_address: 173.26.2.4
    environment:
      - MYSQL_DATABASE=magento
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=123456
    ports:
        - "33106:3306"
    volumes:
      - //c/Users/username/path-here/data:/var/lib/mysql

networks:
  magento:
      ipam:
          driver: default
          config:
              - subnet: 173.26.0.0/16
